### ISSUE TITLE
checkbox fontu görünmüyor.

### ISSUE THREAD

**Issue by betul** [Gnu-linux-turkiye/lnxtr#5]
icomoon font klasoru dahil edilmemiş.

**Comment by Ketcap** [comment]
https://github.com/Gnu-linux-turkiye/lnxtr/commit/d2f0476fc7744eb458e6f253ed7349a77fc77d08  ugur branchine son pushda eklendi bug düzeltildi dosya yolu hatası giderildi :) @betul

**Comment by Ketcap** [comment]
closed
