### ISSUE TITLE
Sass nodejs bindingi olmadigi icin binary patliyor .

### ISSUE THREAD

**Issue by NikosEfthias** [Gnu-linux-turkiye/lnxtr#6]
bu sasstaki bir bug bu gece fark ettim [buradan](https://github.com/sass/node-sass/issues/758) gorebilirsiniz.
`Sass` kisimlarimizi `less` e gecirelim.
Not: grid dosyasi sadece css uzantisini sasstan less e cevirirseniz less olarak compile edilir .

**Comment by betul** [comment]
son durum ?
